# Generated by Django 3.2.8 on 2021-10-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='desciption',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
