# Generated by Django 3.2.8 on 2021-11-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211016_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='/bed.jpeg', null=True, upload_to=''),
        ),
    ]
