products = [
  {
    '_id': "1",
    'name' : "Bed with side tables",
    'images': "/images/products/bedwithsidetable1.jpg",
    'desciption': "Contains 4 big square to keep storage with hydrallic lift",
    'brand': "Base company",
    'category': "Beds",
    'price': 50.99,
    'countInStock': 10,
    'rating': 5.0,
    'numReviews': 12,
  },
  {
    '_id': "2",
    'name': "Sofa set",
    'images': "/images/products/sofaset5.jpg",
    'desciption': "Good product",
    'brand': "Base company",
    'category': "Sofa",
    'price': 53.99,
    'countInStock': 0,
    'rating': 4.8,
    'numReviews': 15,
  },
  {
    '_id': "3",
    'name': "Sofa cum bed",
    'images': "/images/products/sofacumbed3.jpg",
    'desciption': "It contains a bed with sofa ",
    'brand': "Base company",
    'category': "Sofa",
    'price': 65.99,
    'countInStock': 14,
    'rating': 4.5,
    'numReviews': 20,
  },
  {
    '_id': "4",
    'name': "King size Bed",
    'images': "/images/products/bed2.jpg",
    'desciption': "Good product",
    'brand': "Base company",
    'category': "Sofa",
    'price': 45.99,
    'countInStock': 13,
    'rating': 5.0,
    'numReviews': 25,
  },
  {
    '_id': "5",
    'name': "Bed back",
    'images': "/images/products/bedback1.jpg",
    'desciption': "Good product",
    'brand': "Base company",
    'category': "Beds",
    'price': 20.99,
    'countInStock': 15,
    'rating': 4.5,
    'numReviews': 15,
  },
  {
    '_id': "6",
    'name': "Alimirah",
    'images': "/images/products/almirah.jpg",
    'desciption': "Good product",
    'brand': "Base company",
    'category': "Alimrah",
    'price': 25.99,
    'countInStock': 16,
    'rating': 4.8,
    'numReviews': 30,
  },
]
