products = [
  {
    '_id': "1",
    'name' : "Samsung Galaxy m53 5g (8gb ram)",
    'images': "/images/products/samsungm53.png",
    'desciption': "The phone comes with a 120 Hz refresh rate 6.70-inch touchscreen display offering a resolution of 1080x2400 pixels (FHD+). Samsung Galaxy M53 5G is powered by an octa-core MediaTek Dimensity 900 processor that features 2 cores clocked at 2.4GHz and 6 cores clocked at 2GHz. It comes with 8GB of RAM.",
    'brand': "Samsung",
    'category': "Mobile Phone",
    'price': 356.00,
    'countInStock': 4,
    'rating': 5.0,
    'numReviews': 1,
  },
  {
    '_id': "2",
    'name': "Motorola Edge 30",
    'images': "/images/products/edge30.png",
    'desciption': "Motorola Edge 30 mobile was launched on 28th April 2022. The phone comes with a 144 Hz refresh rate 6.50-inch touchscreen display offering a resolution of 1080x2400 pixels (FHD+). Motorola Edge 30 is powered by an octa-core Qualcomm Snapdragon 778G Plus processor. It comes with 6GB, 8GB of RAM.",
    'brand': "Motorola",
    'category': "Mobile Phone",
    'price': 386.18,
    'countInStock': 5,
    'rating': 4.8,
    'numReviews': 1,
  },
  {
    '_id': "3",
    'name': "Sofa cum bed",
    'images': "/images/products/sofacumbed3.jpg",
    'desciption': "It contains a bed with sofa ",
    'brand': "Base company",
    'category': "Sofa",
    'price': 65.99,
    'countInStock': 14,
    'rating': 4.5,
    'numReviews': 20,
  },
  {
    '_id': "4",
    'name': "King size Bed",
    'images': "/images/products/bed2.jpg",
    'desciption': "Good product",
    'brand': "Base company",
    'category': "Sofa",
    'price': 45.99,
    'countInStock': 13,
    'rating': 5.0,
    'numReviews': 25,
  },
  {
    '_id': "5",
    'name': "Bed back",
    'images': "/images/products/bedback1.jpg",
    'desciption': "Good product",
    'brand': "Base company",
    'category': "Beds",
    'price': 20.99,
    'countInStock': 15,
    'rating': 4.5,
    'numReviews': 15,
  },
  {
    '_id': "6",
    'name': "Alimirah",
    'images': "/images/products/almirah.jpg",
    'desciption': "Good product",
    'brand': "Base company",
    'category': "Alimrah",
    'price': 25.99,
    'countInStock': 16,
    'rating': 4.8,
    'numReviews': 30,
  },
]
