const products = [
  {
    '_id': "1",
    'name' : "Samsung Galaxy m53 5g (8gb ram)",
    'images': "/images/products/samsungm53.png",
    'desciption': "The phone comes with a 120 Hz refresh rate 6.70-inch touchscreen display offering a resolution of 1080x2400 pixels (FHD+). Samsung Galaxy M53 5G is powered by an octa-core MediaTek Dimensity 900 processor that features 2 cores clocked at 2.4GHz and 6 cores clocked at 2GHz. It comes with 8GB of RAM.",
    'brand': "Samsung",
    'category': "Mobile Phone",
    'price': 356.00,
    'countInStock': 4,
    'rating': 5.0,
    'numReviews': 1,
  },
  {
    '_id': "2",
    'name': "Motorola Edge 30",
    'images': "/images/products/edge30.png",
    'desciption': "Motorola Edge 30 mobile was launched on 28th April 2022. The phone comes with a 144 Hz refresh rate 6.50-inch touchscreen display offering a resolution of 1080x2400 pixels (FHD+). Motorola Edge 30 is powered by an octa-core Qualcomm Snapdragon 778G Plus processor. It comes with 6GB, 8GB of RAM.",
    'brand': "Motorola",
    'category': "Mobile Phone",
    'price': 386.18,
    'countInStock': 5,
    'rating': 4.8,
    'numReviews': 1,
  },
  {
    '_id': "3",
    'name': "Realme 9 pro",
    'images': "/images/products/realme9pro.png",
    'desciption': "Realme 9 Pro 5G mobile was launched on 16th February 2022. The phone comes with a 120 Hz refresh rate 6.60-inch touchscreen display offering a resolution of 1080x2412 pixels. Realme 9 Pro 5G is powered by an octa-core Qualcomm Snapdragon 695 processor",
    'brand': "Realme",
    'category': "Mobile Phone",
    'price': 270.08,
    'countInStock': 5,
    'rating': 4.5,
    'numReviews': 1,
  },
  {
    '_id': "4",
    'name': "Samsung 43 inch TV ",
    'images': "/images/products/samsung43inch.png",
    'desciption': "Samsung 108 cm (43 inch) Full HD LED Smart TV, 5 Series 43T5350 ; Operating System · Tizen ; Resolution · FHD (1920 x 1080) ; Connectivity · 2 HDMI & 1 USB Ports.",
    'brand': "Samsung",
    'category': "TV",
    'price': 364.12,
    'countInStock': 5,
    'rating': 5.0,
    'numReviews': 1,
  },
  {
    '_id': "5",
    'name': "Dell 3501",
    'images': "/images/products/dell3501.png",
    'desciption': "Dell Inspiron 3501 15.6 inches(39.6cm) FHD Display Laptop (Intel i5-1135G7/8GB/1TB HDD + 256GB SSD/Integrated Graphics/Windows 10 + MSO/Backlit KB/Soft Mint Color) D560412WIN9S, 1.83Kg.",
    'brand': "Dell",
    'category': "Laptop",
    'price': 767,
    'countInStock': 5,
    'rating': 4.5,
    'numReviews': 1,
  },
  {
    '_id': "6",
    'name': "Lenevo X13 thinkpad AMD",
    'images': "/images/products/lenevix13.png",
    'desciption': "Meet the Lenovo ThinkPad X13 Gen 2 (13 AMD), a 13.3 thin & light business laptop with powerful AMD Ryzen™ PRO 5000 series processors",
    'brand': "Lenevo",
    'category': "Laptop",
    'price': 1622.00,
    'countInStock': 5,
    'rating': 4.8,
    'numReviews': 1,
  },
]

export default products